import { GoogleGenAI } from "@google/genai";
import { z } from "zod";
import { zodToJsonSchema } from "zod-to-json-schema";
import { env } from "../config/env.js";
import puppeteer from "puppeteer";
const ai = new GoogleGenAI({
  apiKey: env.GEMINI_API_KEY,
});


const interviewReportSchema = z.object({
  matchScore: z
    .number()
    .describe(
      "A score between 0 and 100 indicating how well the candidate's profile matches the job describe",
    ),
  technicalQuestions: z
    .array(
      z.object({
        question: z
          .string()
          .describe("The technical question may be asked in the interview"),
        intention: z
          .string()
          .describe(
            "The intention of the interviewer behind the technical question",
          ),
        answer: z
          .string()
          .describe(
            "How to answer the technical question, what points to cover in the answer, and what is the appropriate answer to the technical question",
          ),
      }),
    )
    .describe(
      "The technical questions that may be asked in the interview along their intention and answer",
    ),
  behavioralQuestions: z
    .array(
      z.object({
        question: z
          .string()
          .describe("The behavioral question may be asked in the interview"),
        intention: z
          .string()
          .describe(
            "The intention of the interviewer behind the behavioral question",
          ),
        answer: z
          .string()
          .describe(
            "How to answer the behavioral question, what points to cover in the answer, and what is the appropriate answer to the behavioral question",
          ),
      }),
    )
    .describe(
      "The behavioral questions that may be asked in the interview along their intention and answer",
    ),
  skillGaps: z
    .array(
      z.object({
        skill: z.string().describe("The skill that the candidate is lacking"),
        severity: z
          .enum(["low", "medium", "high"])
          .describe("The severity of the skill gap"),
      }),
    )
    .describe("List of skill gaps that the candidate has"),
  preparationPlan: z
    .array(
      z.object({
        day: z.number().describe("The day number of the preparation plan"),
        focus: z
          .string()
          .describe("The focus of the preparation plan for the day"),
        tasks: z.array(
          z
            .string()
            .describe(
              "The tasks that the candidate should do to prepare for the interview on the day",
            ),
        ),
      }),
    )
    .describe(
      "A day-wise preparation plan for the candidate to prepare for the interview  ",
    ),
  title: z
    .string()
    .describe(
      "The title of the job for which the interview report is generated",
    ),
});

export async function generateInterviewReport({
  resume,
  selfDescription,
  jobDescription,
}) {
  const prompt = `
You are an expert interview coach.

Generate an interview preparation report for the candidate based on:
1. Resume
2. Self description
3. Job description

The output MUST strictly follow the provided response schema.

Do not add any properties that are not present in the schema.
Do not rename any properties.
matchScore must be a number between 0 and 100, not a percentage string.

Resume:
${resume}

Self Description:
${selfDescription}

Job Description:
${jobDescription}
`;
  const response = await ai.models.generateContent({
    model: "gemini-3.6-flash",
    contents: prompt,
    config: {
      responseMimeType: "application/json",
      responseJsonSchema: z.toJSONSchema(interviewReportSchema),
    },
  });
  return JSON.parse(response.text);
}


async function convertHtmlToPdf(htmlContent) {
    const browser = await puppeteer.launch();
    const page = await browser.newPage();
    await page.setContent(htmlContent, { waitUntil: 'networkidle0' });

    const pdfBuffer = await page.pdf({ format: 'A4' });
    
    await browser.close();

    return pdfBuffer;

}

export async function generateResumePdf({
  resume,
  selfDescription,
  jobDescription,
}) {
  const resumePdfSchema = z.object({
    html: z
      .string()
      .describe(
        "The html content of the resume which can be converted to pdf using any html to pdf converter library",
      ),
  });

  const prompt = `You are an expert resume writer.
Generate a resume in html format for the candidate based on:
1. Resume: ${resume}
2. Self Description: ${selfDescription}
3. Job Description: ${jobDescription}
response must be a json object with a single property "html" which contains the html content of the resume. The html content must be well formatted and should be ready to be converted to pdf using any html to pdf converter library.
4. The resume should be not sound like it's generated by AI and should be close as possible to a real human-written resume.
5. The resume should be in a single page format and should be visually appealing and should be easy to read.
6. The resume content should be in a single column format and should be easy to read, should not be cluttered with too much information, and use appropriate headings and subheadings to organize the content.
7. Also use appropriate font styles and sizes to make the resume visually appealing and easy to read.
8. Content of the resume should be properly spread out and should not be cluttered with too much information, use appropriate headings and subheadings to organize the content.`;

    const response = await ai.models.generateContent({
      model: "gemini-3.6-flash",
      contents: prompt,
      config: {
        responseMimeType: "application/json",
        responseJsonSchema: z.toJSONSchema(resumePdfSchema),
      },
    });
   const result = JSON.parse(response.text);
   const pdfBuffer = await convertHtmlToPdf(result.html);
   return pdfBuffer;
}


