import React from 'react';
import { useNavigate } from 'react-router';
const ReportCard = ({
  reportId,
  title,
  role,
  createdAt,
  generatedBy,
  matchScore,
  skills = [],
  owner = "Unknown",
}) => {

  const date = new Date(createdAt);
  const options = {
    day: 'numeric',
    month: 'short',
    year: 'numeric',
  }

  const formatedDate = date.toLocaleDateString('en-GB',options);
  const navigate = useNavigate();

  return (
    <article className="report-card" onClick={() => navigate(`/interview/${reportId}`)}>
      <div className="report-card__header">
        <div className="report-card__info">
          <h3>{title}</h3>
          <p className="report-card__role">{role}</p>
          <p className="report-card__meta">
            {formatedDate} <span>•</span> Generated by: {owner}
          </p>
        </div>

        <div className="report-card__score" aria-label={`${matchScore}% match score`}>
          <span>{matchScore}</span>
        </div>
      </div>

      <div className="report-card__skills">
        {skills.map((skill) => (
          <span key={skill.skill} className="report-card__skill">
            {skill.skill}
          </span>
        ))}
      </div>
    </article>
  );
};

export default ReportCard;
